name: Python Scheduled Script

on:
  schedule:
    - cron: '0 6 * * *'  # every day at 6 AM UTC
  workflow_dispatch:

jobs:
  daily_tracker:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run daily tracker
      run: |
        python src/data_fetcher.py

    - name: Push changes
      run: |
        git config --local user.email "noushadchowdhury30@hotmail.com"
        git config --local user.name "noushad223"
        git add onepiece_tracker.csv
        git diff-index --quiet HEAD || git commit -m "Update One Piece tracker [skip ci]"
        git push origin HEAD:main
