name: Python Scheduled Script

on:
  schedule:
    - cron: '0 6 * * *'  # every day at 6 AM UTC
  workflow_dispatch:

jobs:
  daily_tracker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run daily tracker
      run: |
        python src/data_fetcher.py

    - name: Commit CSV if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add onepiece_tracker.csv
        git diff-index --quiet HEAD || (git commit -a -m "Updated One Piece tracker using GH Actions cronjob [skip ci]" --allow-empty)

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: cronjobs
